Feat/leaderboards
jala-game/spaceinvaders pull request #28
Opened 2024-02-23 21:34 UTC by iure06

Add logic for draw the leader boards and implement the pagination

2024-02-23 22:19 UTC, Williancc1557 commented on spaceinvaders/src/model/ColorLeaderBoards.cs
Coloca esse ColorLeaderBoards dentro do diretório screen/LeaderBoardScreen/

2024-02-23 23:39 UTC, vinycalves requested changes
O código está muito bem estruturado, se der para dar alguns ajustes ficará perfeito.

2024-02-23 23:39 UTC, vinycalves commented on spaceinvaders/src/screen-logic/screens/LeaderBoardsScreen/ColorLeaderBoards.cs
> +        colors.Shuffle(new Random());
Se for possível coloca o inverse dele, sendo
```cs
if (colors != null) return;
```

2024-02-23 23:39 UTC, vinycalves commented on spaceinvaders/src/screen-logic/screens/LeaderBoardsScreen/LeaderBoardsScreen.cs
> +                break;
Modifique de inteiro para o valor do tipo do **Enum** mesmo, facilita a inserção do código. E quando precisar do valor basta fazer o wrapping do objeto.

2024-02-23 23:39 UTC, vinycalves commented on spaceinvaders/src/utils/LocalStorage.cs
> +    }
Essa função está tratando dados de um Json, então é bom tratar as possíveis exceções dela, tenta colocar um **try&catch** no código e utilize um LINQ para o foreach
```cs
data?.ForEach(userData => users.Add(userData.ToObject<User>()));
```

2024-02-23 23:39 UTC, vinycalves commented on spaceinvaders/src/services/EScreenMenuOptionsGameOver.cs
Pode deixar os valores como 0,1,2,3, esse Enum é único para essa tela.

2024-02-23 23:43 UTC, vinycalves commented on spaceinvaders/src/screen-logic/screens/LeaderBoardsScreen/LeaderBoardsScreen.cs
> +    private int _chooseMenu = 7;
Precisa mudar para o tipo de 
```cs
private EScreenMenuOptionsGameOver _choosedMen = EScreenMenuOptionsGameOver.RightArrow;
```

2024-02-24 01:05 UTC, Williancc1557 requested changes

2024-02-24 01:05 UTC, Williancc1557 commented on spaceinvaders/src/screen-logic/screens/LeaderBoardsScreen/ColorLeaderBoards.cs
Mover esse arquivo para models/screens/LeaderBoardsScreen

2024-02-24 01:17 UTC, Williancc1557 approved these changes

2024-02-24 01:17 UTC, Williancc1557 commented on spaceinvaders/src/screen-logic/screens/LeaderBoardsScreen/LeaderBoardsScreen.cs
Deixar esse arquivo como estava antes dentro da pasta screens

2024-02-24 01:17 UTC, Williancc1557 commented on spaceinvaders/src/screen-logic/screens/LeaderBoardsScreen/ColorLeaderBoards.cs
Mover esse arquivo para models/screens/LeaderBoardsScreen

2024-02-24 01:18 UTC, merged